---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Danielle Navarro: Selected Manuscripts

This is not a complete listing of all my papers (you can find that on my
website [here](https://compcogscisydney.org/publications)). Instead it
is a collection of papers that I thought were worth the effort of
recovering and rebuilding from source so that the paper spells my name
correctly. At the moment there are a few papers listed but in the readme
but not in the repository. This is because I have not yet managed to
track down the source and rebuild the manuscripts with the proper name.

This repository includes both the final pdf file in the `manuscript`
folder, and the `source` files used to generate it. In each case the
citation below links to the journal DOI for the version of record, but
if anyone wishes to share copies of my older papers *without* deadnaming
me in the process, you can use the versions hosted here\! Additionally,
my papers are sometimes associated with supplementary materials, data
sets, analyses etc, hosted on OSF or GitHub, or with a preprint (or
postprint) posted to PsyArXiv. Whenever that is the case, I have linked
to those here.

## 2019

  - De Deyne, S., Navarro, D. J., Perfors, A., Brysbaert, M. and Storms,
    G. (2019). The Small World of Words: English word association norms
    for over 12,000 cue words. *Behavior Research Methods, 51*, 987-1006
    [[pdf](./manuscripts/2019_swow.pdf), [source](./source/2019_swow/),
    [doi](https://doi.org/10.3758/s13428-018-1115-7)]
  - Hayes, B. K., Banner, S., Forrester, S. and Navarro, D. J. (2019).
    Selective sampling and inductive inference: Drawing inferences based
    on observed and missing evidence. *Cognitive Psychology, 113*.
    [[pdf](./manuscripts/2019_samplingframes.pdf),
    [source](./source/2019_samplingframes),
    [doi](https://doi.org/10.1016/j.cogpsych.2019.05.003),
    [psyarxiv](https://doi.org/10.17605/OSF.IO/2M83V),
    [github](https://github.com/djnavarro/samplingframes)]
  - Hayes, B. K., Navarro, D. J., Stephens, R., Ransom, K. and Dilevski,
    N. (2019). The diversity effect in inductive reasoning depends on
    sampling assumptions. *Psychonomic Bulletin & Review, 26*,
    1043-1050. [[pdf](./manuscripts/2019_diversitysampling.pdf),
    [source](./source/2019_diversitysampling),
    [doi](https://doi.org/10.3758/s13423-018-1562-2),
    [osf](https://osf.io/fpx9k/),
    [github](https://github.com/djnavarro/samplingframes)]
  - Hendrickson, A., Perfors, A., Navarro, D. J. and Ransom, K. (2019).
    Sample size, number of categories and sampling assumptions:
    Exploring some differences between categorization and
    generalization. *Cognitive Psychology, 111*, 80-102
    [[pdf](./manuscripts/2019_onecattwocat.pdf),
    [source](./source/2019_onecattwocat),
    [doi](https://dx.doi.org/10.1016/j.cogpsych.2019.03.001),
    [psyarxiv](https://psyarxiv.com/9vc2n/)]
  - Lee, J. C., Lovibond, P. F., Hayes, B. K. and Navarro, D. J. (2019).
    Negative evidence and inductive reasoning in generalization of
    associative learning. *Journal of Experimental Psychology: General*,
    148, 289-303. [[pdf](./manuscripts/2019_negevassoc.pdf)]
  - Navarro, D. J. (2019). Between the devil and the deep blue sea:
    Tensions between scientific judgement and statistical model
    selection. *Computational Brain and Behavior, 2*, 28-34
    [[pdf](./manuscripts/2019_devildeepbluesea.pdf),
    [source](./source/2019_devildeepbluesea),
    [doi](https://doi.org/10.1007/s42113-018-0019-z),
    [osf](https://osf.io/5swnm/),
    [psyarxiv](https://psyarxiv.com/39q8y/)]
  - Vong, W. K., Hendrickson, A., Navarro, D. J. and Perfors, A. (2019).
    Do additional features help or hurt category learning? The curse of
    dimensionality in human learners. *Cognitive Science, 43*, e12724
    [[pdf](./manuscripts/2019_curse.pdf),
    [source](./source/2019_curse),
    [doi](http://dx.doi.org/10.1111/cogs.12724),
    [psyarxiv](https://dx.doi.org/10.17605/OSF.IO/BJH68)]

## 2018

  - Langsford, S., Perfors, A., Hendrickson, A., Kennedy, L. and
    Navarro, D. J. (2018). A systematic comparison and reliability
    analysis of formal measures of sentence acceptability. *Glossa: A
    Journal of General Linguistics, 3*, 37.
    [[pdf](./manuscripts/2018_grammaticality.pdf),
    [source](./source/2018_grammaticality),
    [doi](http://doi.org/10.5334/gjgl.396)]
  - Martire, K. A., Growns, B. and Navarro, D. J. (2018). What do the
    experts know? Calibration, precision, and the wisdom of crowds among
    forensic handwriting experts. *Psychonomic Bulletin and Review, 25*,
    2346–2355. [[pdf](./manuscripts/2018_handwriting.pdf),
    [source](./source/2018_handwriting),
    [doi](https://doi.org/10.3758/s13423-018-1448-3),
    [osf](https://osf.io/n2g4v/),
    [github](https://github.com/djnavarro/handwritingwoc)]
  - Navarro, D. J., Perfors, A., Kary, A., Brown, S. and Donkin, C.
    (2018). When extremists win: Cultural transmission via iterated
    learning when priors are heterogeneous. *Cognitive Science, 42*,
    2108-2149. [[pdf](./manuscripts/2018_extremists.pdf),
    [source](./source/2018_extremists),
    [doi](http://dx.doi.org/10.1111/cogs.12667),
    [psyarxiv](http://dx.doi.org/10.17605/OSF.IO/7NPQ6),
    [osf](https://osf.io/2xq5k/),
    [github](https://github.com/djnavarro/mixedchains)]
  - Navarro, D. J., Tran, P. and Baz, N. (2018). Aversion to option loss
    in a restless bandit task. *Computational Brain and Behavior, 1*,
    151-164. [[pdf](./manuscripts/2018_vanishingbandits.pdf),
    [source](./source/2018_vanishingbandits),
    [doi](https://dx.doi.org/10.1007/s42113-018-0010-8),
    [psyarxiv](https://doi.org/10.17605/OSF.IO/3G4P5),
    [osf](https://osf.io/nzvqp/)]

## 2017

  - Kennedy, L., Navarro, D. J., Perfors, A. and Briggs, N. (2017). Not
    every credible interval is credible: Evaluating robustness in the
    presence of contamination in Bayesian data analysis. *Behavior
    Research Methods, 49*, 2219–2234.
    [[pdf](./manuscripts/2017_robustintervals.pdf),
    [source](./source/2017_robustintervals),
    [doi](https://doi.org/10.3758/s13428-017-0854-1)]
  - Martire, K. A., Edmond, G., Navarro, D. J, and Newell, B. R. (2017).
    On the likelihood of ‘encapsulating all uncertainty’. *Science and
    Justice, 57*, 76-79 [[pdf](./manuscripts/2017_scijust.pdf),
    [source](./source/2017_scijust/),
    [doi](https://doi.org/10.1016/j.scijus.2016.10.004)]
  - Navarro, D. J. and Kemp, C. (2017). None of the above: A Bayesian
    account of the detection of novel categories. *Psychological Review,
    124*, 643-677 [[pdf](./manuscripts/2017_noneoftheabove.pdf),
    [source](./source/2017_noneoftheabove/),
    [doi](https://doi.org/10.1037/rev0000077)]
  - Tauber, S., Navarro, D. J., Perfors A. and Steyvers, M. (2017).
    Bayesian models of cognition revisited: Setting optimality aside and
    letting data drive psychological theory. *Psychological Review,
    124*, 410-441 [[pdf](./manuscripts/2017_descriptivebayes.pdf),
    [source](./source/2017_descriptivebayes/),
    [doi](https://doi.org/10.1037/rev0000052)]

## 2016

  - De Deyne, S., Kenett, Y. N., Anaki, D., Faust, M. and Navarro, D. J.
    (2016). Large-scale network representations of semantics in the
    mental lexicon. In M. N. Jones (Ed.) *Big Data in Cognitive Science:
    From Methods to Insights* (pp. 174-202)
  - De Deyne, S., Navarro D. J., Perfors, A. and Storms, G. (2016).
    Structure at every scale: A semantic network account of the
    similarities between very unrelated concepts. *Journal of
    Experimental Psychology: General, 145*, 1228-1254
    [[pdf](./manuscripts/2016_weaksimilarity.pdf),
    [source](./source/2016_weaksimilarity/),
    [doi](https://doi.org/10.1037/xge0000192)]
  - Gokaydin, D. Navarro, D. J., Ma-Wyatt, A. and Perfors, A. (2016).
    The structure of sequential effects. *Journal of Experimental
    Psychology: General, 145*, 110-123
    [[pdf](./manuscripts/2016_sequential.pdf),
    [source](./source/2016_sequential/),
    [doi](http://dx.doi.org/10.1037/xge0000106)]
  - Hendrickson, A., Navarro D. J. and Perfors, A. (2016). Sensitivity
    to hypothesis size during information search. *Decision, 3*, 62-80.
    [[pdf](./manuscripts/2016_battleships.pdf)]
  - Navarro, D. J., Newell, B. and Schulze, C. (2016). Learning and
    choosing in an uncertain world: An investigation of the
    explore-exploit dilemma in static and dynamic environments.
    *Cognitive Psychology, 85*, 43-77.
    [[pdf](./manuscripts/2016_exploreexploit.pdf),
    [source](./source/2016_exploreexploit/),
    [doi](https://doi.org/10.1016/j.cogpsych.2016.01.001),
    [github](https://github.com/djnavarro/observeorbet)]
  - Ransom, K., Perfors, A. and Navarro, D. J. (2016). Leaping to
    conclusions: Why premise relevance affects argument strength.
    *Cognitive Science, 40*, 1775-1796
    [[pdf](./manuscripts/2016_samplinginreasoning.pdf),
    [source](./source/2016_samplinginreasoning/),
    [doi](https://doi.org/10.1111/cogs.12308)]
  - Vong, W. K., Navarro, D. J. and Perfors, A. (2016). The helpfulness
    of category labels in semi-supervised learning depends on category
    structure. *Psychonomic Bulletin and Review, 23*, 230-238
    [[pdf](./manuscripts/2016_semisupervised.pdf),
    [source](./source/2016_semisupervised/),
    [doi](https://dx.doi.org/10.3758/s13423-015-0857-9)]

## 2015

  - Voorspoels, W., Navarro, D. J., Perfors, A., Ransom K. and Storms,
    G. (2015). How do people learn from negative evidence? Non-monotonic
    generalizations and sampling assumptions in inductive reasoning.
    *Cognitive Psychology, 81*, 1-25.
    [[pdf](./manuscripts/2015_negativeevidence.pdf),
    [source](./source/2015_negativeevidence/),
    [doi](http://dx.doi.org/10.1016/j.cogpsych.2015.07.001)]

## 2014

  - De Deyne, S., Voorspoels, W., Verheyen, S., Navarro, D. J. and
    Storms, G. (2014). Accounting for graded structure in adjective
    categories with valence-based opposition relationships. *Language
    and Cognitive Processes, 29*, 568-583.
    [[pdf](./manuscripts/2014_adjectives.pdf),
    [source](./source/2014_adjectives/),
    [doi](http://dx.doi.org/10.1080/01690965.2013.794294),
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/9bfrd)]
  - Perfors, A. and Navarro, D. J. (2014). Language evolution can be
    shaped by the structure of the world. *Cognitive Science, 38*,
    775-793 [[pdf](./manuscripts/2014_iterated.pdf),
    [source](./source/2014_iterated/),
    [doi](http://dx.doi.org/10.1111/cogs.12102)]

## 2013

  - De Deyne, S., Navarro, D. J. and Storms, G. (2013). Better
    explanations of lexical and semantic cognition using networks
    derived from continued rather than single word associations.
    *Behavior Research Methods, 45*, 480-498.
    [[pdf](./manuscripts/2013_swow.pdf), 
    [source](./source/2013_swow/),
    [doi](http://dx.doi.org/10.3758/s13428-012-0260-7),
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/kumwj)]

## 2012

  - Navarro, D. J., Dry, M. J. and Lee, M D. (2012). Sampling
    assumptions in inductive generalization. *Cognitive Science, 36*,
    187-223 [[pdf](./manuscripts/2012_samplingassumptions.pdf),
    [source](./source/2012_samplingassumptions/),
    [doi](http://dx.doi.org/10.1111/j.1551-6709.2011.01212.x),
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/ab2x6)]
  - Shafto, P., Eaves, B., Navarro, D. J. and Perfors, A. (2012).
    Epistemic trust: Modeling children’s reasoning about others’
    knowledge and intent. *Developmental Science, 15,* 436-447.
    [[pdf](./manuscripts/2012_epistemictrust.pdf), 
    [doi](http://dx.doi.org/10.1111/j.1467-7687.2012.01135.x),
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/v8z7x)]

## 2011

  - Navarro, D. J. and Perfors, A. (2011). Hypothesis generation, the
    positive test strategy, and sparse categories. *Psychological
    Review, 118*, 120-34 [[pdf](./manuscripts/2011_positivetest.pdf),
    [source](./source/2011_positivetest/),
    [doi](http://dx.doi.org/10.1037/a0021110),
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/rj9kt)]

## 2010

  - Navarro, D. J. and Perfors, A. (2010). Similarity, feature
    discovery, and the size principle. *Acta Psychologica, 133*, 256-268
    [[pdf](./manuscripts/2010_featurediscovery.pdf),
    [source](./source/2010_featurediscovery/),
    [doi](http://dx.doi.org/10.1016/j.actpsy.2009.10.008), 
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/da4wb)]
  - Sanborn, A. N., Griffiths, T. L. and Navarro, D. J. (2010). Rational
    approximations to rational models: Alternative algorithms for
    category learning. *Psychological Review, 117*, 1144-1167.
    [[pdf](./manuscripts/2010_particlefilters.pdf), 
    [doi](https://dx.doi.org/10.1037/a0020511),
    [psyarxiv](https://dx.doi.org/10.31234/osf.io/qj42m)]

## 2009

  - Navarro, D. J. and Fuss, I. (2009). Fast and accurate calculations
    for first-passage times in Wiener diffusion models. *Journal of
    Mathematical Psychology, 53*, 222-230.
    [[pdf](./manuscripts/2009_firstpassage.pdf), 
    [doi](https://doi.org/10.1016/j.jmp.2009.02.003),
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/4v9xt)]
  - Grunwald, P. and Navarro, D. J. (2009). NML, Bayes and true
    distributions: A comment on Karabatsos and Walker (2006). *Journal
    of Mathematical Psychology, 53*, 43-51.
    [[pdf](./manuscripts/2009_nmlbayes.pdf),
    [source](./source/2009_nmlbayes/),
    [doi](http://dx.doi.org/10.1016/j.jmp.2008.11.005), 
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/szv7n)]


## 2008

  - Navarro, D. J. and Griffiths, T. L. (2008). Latent features in
    similarity judgments: A nonparametric Bayesian approach. *Neural
    Computation, 20*, 2597-2628.
    [[pdf](./manuscripts/2008_ibpadclus.pdf),
    [source](./source/2008_ibpadclus/),
    [doi](http://dx.doi.org/10.1162/neco.2008.04-07-504),
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/47cz2)]

## 2007

  - Griffiths, T. L., Canini, K. R., Sanborn, A. N. and Navarro, D. J.
    (2007). Unifying rational models of categorization via the
    hierarchical Dirichlet process. In D. S. McNamara and J. G. Trafton
    (Eds) *Proceedings of the 29th Annual Conference of the Cognitive
    Science Society* (pp. 323-328).
    [[pdf](./manuscripts/2007_hdp.pdf),
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/ketw3)]
  - Myung, J. I., Pitt, M. A. and Navarro, D. J. (2007). Does response
    scaling cause the Generalized Context Model to mimic a prototype
    model? *Psychonomic Bulletin and Review, 14*, 1043-1050.
    [[pdf](./manuscripts/2007_catmimic.pdf),
    [source](./source/2007_catmimic/),
    [doi](http://dx.doi.org/10.3758/BF03193089),
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/ucrq3)]

## 2006

  - Myung, J. I., Navarro, D. J. and Pitt, M. A. (2006). Model selection
    by Normalized Maximum Likelihood. *Journal of Mathematical
    Psychology, 50*, 167-179. 
    [[pdf](./manuscripts/2006_nml.pdf),
    [source](./source/2006_nml/),
    [doi](http://dx.doi.org/10.1016/j.jmp.2005.06.008),
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/evtxa)]
  - Navarro, D. J., Griffiths, T. L., Steyvers, M. and Lee, M. D.
    (2006). Modeling individual differences using Dirichlet processes.
    *Journal of Mathematical Psychology, 50*, 101-122.
    [[pdf](./manuscripts/2006_indivdiffs.pdf),
    [source](./source/2006_indivdiffs/),
    [doi](http://dx.doi.org/10.1016/j.jmp.2005.11.006),
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/bc3ya)]
  - Pitt, M. A., Kim, W., Navarro, D. J. and Myung, J. I. (2006). Global
    model analysis by parameter space partitioning. *Psychological
    Review, 113*, 57-83. 
    [[pdf](./manuscripts/2006_psp.pdf),
    [doi](http://dx.doi.org/10.1037/0033-295X.113.1.57),
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/43auj)]

## 2005

  - Lee, M. D. and Navarro, D. J. (2005). Minimum description length and
    psychological clustering models. In P. Grunwald, I. J. Myung and M.
    A. Pitt (Eds) *Advances in Minimum Description Length: Theory and
    Applications* (pp. 355-384).
    [[pdf](./manuscripts/2005_mdlclustering.pdf),
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/s4vbz)]

## 2004

  - Navarro, D. J. (2004). A note on the applied use of MDL
    approximations. *Neural Computation, 16*, 1763-1768.
    [[pdf](./manuscripts/2004_mdlnote.pdf),
    [source](./source/2004_mdlnote/),
    [doi](http://dx.doi.org/10.1162/0899766041336378), 
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/upf42)]
  - Navarro, D. J. and Lee, M. D. (2004). Common and distinctive
    features in stimulus representation: A modified version of the
    contrast model. *Psychonomic Bulletin and Review, 11*, 961-974. 
    [[pdf](./manuscripts/2004_contrastmodel.pdf),
    [doi](http://dx.doi.org/10.3758/BF03196728),
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/pq5kr)]
  - Navarro, D. J., Pitt, M. A. and Myung, I. J. (2004). Assessing the
    distinguishability of models and the informativeness of data.
    *Cognitive Psychology, 49*, 47-84
    [[pdf](./manuscripts/2004_informativeness.pdf),
    [source](./source/2004_informativeness/),
    [doi](http://dx.doi.org/10.1016/j.cogpsych.2003.11.001),
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/7u3vc)]

## 2003

  - Navarro, D. J. (2003). Regarding the complexity of additive
    clustering models: Comment on Lee (2001). *Journal of Mathematical
    Psychology, 47*, 241-243.
    [[pdf](./manuscripts/2003_adclusnote.pdf),
    [source](./source/2003_adclusnote/),
    [doi](http://dx.doi.org/10.1016/S0022-2496%2802%2900026-3),
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/akbyv)]
  - Navarro, D. J. and Lee, M. D. (2003). Combining dimensions and
    features in similarity-based representations. In S. Becker, S. Thrun
    and K. Obermayer (Ed.) *Advances in Neural Information Processing
    Systems* (pp. 67-74). 
    [[pdf](./manuscripts/2003_hybridsimilarity.pdf),
    [psyarxiv](http://dx.doi.org/10.31234/osf.io/qejyb)]

## 2002

  - Lee, M. D. and Navarro, D. J. (2002). Extending the ALCOVE model of
    category learning to featural stimulus domains. *Psychonomic
    Bulletin and Review, 9*, 43-58. [[pdf](./manuscripts/2002_alcove.pdf),
    [doi](https://doi.org/10.3758/BF03196256),
    [psyarxiv](https://dx.doi.org/10.31234/osf.io/uvtbf)]

## Books

I’m not really sure how all the *Learning Statistics with {{Software}}*
books fit into an academic publication list. They seem to sit in their
own world rather distinct from traditional publication. Anyway, here
they are:

  - Navarro, D. J. and Foxcroft D. R. (2019). *Learning statistics with
    jamovi: A tutorial for psychology students and other beginners.*
    [[site](https://doi.org/10.24384/hgc3-7p15)]
  - Navarro, D. J., Foxcroft D. R. and Faulkenberry, T. J. (2019).
    *Learning statistics with JASP: A tutorial for psychology students
    and other beginners.* [[site](https://learnstatswithjasp.com/)]
  - Navarro, D. J. (2015). *Learning statistics with R: A tutorial for
    psychology students and other beginners*.
    [[site](https://learningstatisticswithr.com)]
